### ISSUE TITLE
Rename Package

### ISSUE THREAD

**Issue by ghost** [gabrielecappellaro/DroidInfo#3]
Change droidinfo.k4ppaj.it to droidinfo.app (it.k4ppaj.droidinfo) -> (app.droidinfo)

**Comment by ghost** [comment]
Oh damn, we must move droidinfo (dir) above k4ppaj (dir) and then remove k4ppaj (dir), after that make it app.

**Comment by ghost** [comment]
obvious also gradle file must be changed.

**Comment by cappee** [comment]
@StopCopyAnything Will you do this?

**Comment by ghost** [comment]
Done, try the branch new_package and see if it works. If yes merge it.
