### ISSUE TITLE
RecyclerView 

### ISSUE THREAD

**Issue by ghost** [gabrielecappellaro/DroidInfo#8]
We may add some shortcut as:

- long press
- double tap

And they'll be selectable by the settings

@gabrielecappellaro

**Comment by cappee** [comment]
Sorry but the tabs are swipeable so with the left, or right, swipe there would be conflicts

**Comment by ghost** [comment]
Oh that's true

**Comment by ghost** [comment]
Tomorrow i'll fix the bug, don't worry

**Comment by ghost** [comment]
Done.
